<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1 (Total recall) ☻

|Term|Brief description|
|:--|:--|
|Subsetting|selecting element(s)|
|Indexing|selects one elememt from a list/array|
|Slicing|can select more than one elememt from a list/array|
|Masking|selects elements that satisfy a given condition or answers questions using True/False|

## Exercise 2 (Show me the ‘odd’ letters) ☻



astype() is used to convert the data types of elements within a NumPy array into a specific data type. 

In [2]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [ ]:
new = np_array_2d[:,0] #Subset all the first elements
new_int = new.astype(int) #Convert to integers
new_int2 = new_int%2 #use % to get the remainder for division by 2
mask = new_int2 == 1 # mask that checks if the remainder is zero or not
print(mask)
second_element = np_array_2d[:,1] # array with all the second elememts
print(second_element[mask]) # apply mask on the second element array

[ True  True False False  True  True False False False  True]
['A' 'C' 'E' 'G' 'I']


## Exercise 3  



In [35]:
x = [[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]
np_array = np.array(x)
mask = np_array < 50 # change values below 50 to -1
np_array[mask] = -1
mask2 = np_array > 50 # change values above 50 to +1
np_array[mask2] = +1
mask3 = np_array == 50 # change values equal to 50 to 0
np_array[mask3] = 0
print(np_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
