<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [4]:
import numpy as np

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

indexing and slicing are forms of subsetting

indexing: picking an element

slicing: selecting a range of elements

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

need to indicate where to start and end in slicing

applies for both lists and arrays

list_name[x:y]
this will return y - x elements
[0] gives you the first element

In [ ]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
np_array = np.array(py_list)

py_list[:5] # Index 0 to index 4

['a1', 'b2', 'c3', 'd4', 'e5']

In [ ]:
py_list[5:] # Index 5 to the end

['f6', 'g7', 'h8', 'i9', 'j10']

In [ ]:
py_list[::-1] # reverses the list

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

In [ ]:
py_list[::1]

['a1', 'b2', 'c3', 'd4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10']

In [6]:
py_list[5:2:-1] # Index 5 to 3 in reverse

['f6', 'e5', 'd4']

In [15]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = np_array % 3 == 0
np_array[mask]

array([3, 6, 9])

In [ ]:
mask

array([False, False,  True, False, False,  True, False, False,  True,
       False])

In [ ]:
mask.sum() #calculates sum of Trues

np.int64(3)

In [ ]:
np_array//2 #Quotient

array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5])

In [ ]:
np_array[~mask] #gives elements that are False

array([ 1,  2,  4,  5,  7,  8, 10])

In [ ]:
np_array[(np_array>3) & (np_array<8)] # "&" means "AND"

array([4, 5, 6, 7])

In [ ]:
np.logical_and(np_array>3,np_array<3)

array([False, False, False, False, False, False, False, False, False,
       False])

## 1.2 Arrays only | Subsetting by masking

In [7]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

The answer to my question is in the form of a ‘Yes’/‘No’ or True/False format. I can use this True/False format to ask NumPy to show me only those that are True by:



In [8]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [10]:
# Alternatively, 
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'
# ~ inverts the mask

array([1, 2, 3])

In [11]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [13]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'
# OR will show something if either mask is True

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

The differences between lists and arrays become even more apparent with higher dimensional lists and arrays. Especially when you try indexing and slicing in higher dimensions.



In [5]:
#2d list
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [ ]:
# What is at position 4?
print(py_list_2d[3])
print(np_array_2d[3])

[4, 'D']
['4' 'D']


In [17]:
# First element at position 4
print(py_list_2d[3][0])
print(np_array_2d[3, 0])

4
4


In [19]:
# What are the first 3 elements?
print(py_list_2d[:3])
print(np_array_2d[:3])

[[1, 'A'], [2, 'B'], [3, 'C']]
[['1' 'A']
 ['2' 'B']
 ['3' 'C']]


In [ ]:
print(py_list_2d[:3][0]) # takes the first 3 elements and then the first out of the 3 elements
print(np_array_2d[:3, 0]) # first element in each of the first 3 elements

[1, 'A']
['1' '2' '3']


In [6]:
print(py_list_2d[3:6][0])
print(np_array_2d[3:6, 0])
print(np_array_2d[:, 0])

[4, 'D']
['4' '5' '6']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [24]:
np_array_2d[3,0] #only for numpy

np.str_('4')

In [26]:
np_array_2d[3:,0] #only for numpy

array(['4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [7]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [27]:
x = [1,2] +[3]
print(x)
x += [4]
print(x)
x += [5]
print(x)
x += [6]
print(x)

[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]


In [ ]:
x = [1, 2]
print(x)
x.append(3)
print(x)
x.append(4)
print(x)

# append() runs faster

[1, 2]
[1, 2, 3]
[1, 2, 3, 4]


In [10]:
x = [1, 2, 3]
x += [4, 5, 6]
print(x)

x=[1, 2, 3]
x.extend([4, 5, 6])
print(x)

x=[1, 2, 3]
x.append([4, 5, 6])
print(x)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, [4, 5, 6]]


# Some loose ends

## 1.5 Tuples

Tuples are similar to lists, except they use ( ) and cannot be changed after creation (i.e., they are immutable).


In [11]:
a = (1, 2, 3) # tuple, tuple cannot be changed
b = [1, 2, 3] # list, list can be changed

# accessing tuple data
print(a[0])    # Access data

1


In [12]:
# Data cannot be changed
# The following will NOT work
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

In [33]:
b + [1]

[1, 2, 3, 1]

## 1.6 Be VERY careful when copying

### Make copies of your list properly!!

In [13]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [14]:
# correct way
x=[1, 2, 3]
y=x.copy()
z=x.copy()

In [ ]:
print(f"{x=}", f"{y=}", f"{z=}")

x=[1, 2, 3] y=[1, 2, 3] z=[1, 2, 3]


In [39]:
x.append(1)
print(f"{x=}", f"{y=}", f"{z=}")

# never edit the tuple directly 

x=[1, 2, 3, 1, 1, 1] y=[1, 2, 3, 1, 1, 1] z=[1, 2, 3, 1, 1, 1]


## Footnotes